[package]
name = "checkmate"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

    [profile.dev.package."*"]
    opt-level = 3


[dependencies]
bevy = { version = "0.18", features = ["serialize", "jpeg", "tga"] }
bevy-inspector-egui = "0.36"
bevy_obj = "0.18"
clap = { version = "4.5", features = ["derive"] }
config-load = "0.1"
derive_more = { version = "2.1", features = ["debug"] }
iyes_perf_ui = { git = "https://github.com/blip-radar/iyes_perf_ui.git", branch = "bevy-0-18" }
fastrand = "2"
serde = { version = "1.0", features = ["derive"] }
